### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by jaynal83** [SparkIQ-Labs/Demos#1]
Hi, I was trying to run demo-1 but getting the following error during run. Can  you please suggest why this is error is producing?
1)
Error in as.data.frame.default(data) : 
  cannot coerce class "structure("DataFrame", package = "SparkR")" to a data.frame

2)
Error in writeJobj(con, object) : invalid jobj 1
Warning: closing unused connection 5 (raw(0))

So far I find out the first error is producing during model fit. Actually it is not accepting the iris_DF object which has difference class.

Looking forward to hear back from you.

Regards
Jaynal

**Comment by Emaasit** [comment]
@jaynal83 Which Spark version are using? You should be using Spark 1.5 or later that provides for fitting  linear models. Let me know.

**Comment by jaynal83** [comment]
Thanks for response. I was using Spark 1.4.1 but based on your response I tried 1.5.2 and it is working.

**Comment by Emaasit** [comment]
@jaynal83 Glad to hear that. If you have any comments after running the demo, just let me know.

**Comment by jaynal83** [comment]
Right at the moment I am running this demo and trying to understand gain over simply shiny. My understanding is that we could gain speed for big data but is there any way to assess that? Are you going to cover that part in your next demo? thanks

**Comment by Emaasit** [comment]
Not really speed. The perfect use case is for when you wan to use all your big data for machine learning but this data cannot fit on a single machine. So you need to distribute it on several machines. If this is the case, then you need to run distributed and parallel algorithms on your distributed data.

**Comment by Sarangam** [comment]
Hi,

I am facing the Error in as.data.frame.default(data) : 
cannot coerce class "structure("DataFrame", package = "SparkR")" to a data.frame when running random forest algorithm.Can you suggest me other multi classification algorithms that run on sparkr data frame?.
